polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

webapp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^webapp/', include('webapp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic

from polls.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after sucessfully
        # dealing with POST data. This prevents data from being posted
        # twice if a user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/detail.html
<head>
{% load bootstrap_toolkit %}

{% bootstrap_stylesheet_tag %}
{% bootstrap_stylesheet_tag "responsive" %}
{% bootstrap_javascript_tag %}
</head>

<body>

{% if error_message %}
<p>
    <div class="alert alert-danger">
<!--        <button type="button" class="close" data-dismiss="alert">&times;</button> -->
        {{error_message}}
    </div>
</p>
{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post" class="form-vertical">
{% csrf_token %}
{{ form|as_bootstrap }}
    <fieldset>
        <legend>{{ poll.question }}</legend>
        <div class="form-group" >
            <div class="form-actions">
                <div class="radio">
                {% for choice in poll.choice_set.all %}
                    <label>
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
                        {{ choice.choice_text }}
                    </label>
                    <br>
                {% endfor %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Vote</button>
        </div>
    </fieldset>
</form>
</body>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<head>
{% load bootstrap_toolkit %}

{% bootstrap_stylesheet_tag %}
{% bootstrap_stylesheet_tag "responsive" %}
</head>

<body>

<legend>{{ poll.question }}</legend>

<ul class="list-group">
{% for choice in poll.choice_set.all %}
    <li class="list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a class="btn btn-primary" href="{% url 'polls:detail' poll.id %}">Vote again?</a>
</body>